In [1]:
import numpy as np

In [34]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    A = np.random.random((n,1))
    return A

def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random((h,w))
    B = np.random.random((h,w))
    s = np.add(A,B)
    
    return A, B, s


def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = np.linalg.norm(np.add(A, B))
    return s


def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    out = np.tanh(np.matmul(weights.T, inputs))
    return out

def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    if x <= y:
        return x*y
    elif y == 0:
        return "Can't divide by zero"
    else:
        return x/y

def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    new_vec_fn = np.vectorize(scalar_function)
    return new_vec_fn(x, y)



In [35]:
if __name__ == '__main__':
#     Testing
    print(randomization(5))
    oA, oB, oS = operations(2, 3)
    print(oA)
    print(oB)
    print(oS)
    print(norm(oA, oB))
    print(neural_network(oA, oB))
    print(scalar_function(5, 6))
    print(vector_function(oA, oB))

[[0.51670107]
 [0.13852331]
 [0.37572255]
 [0.48035179]
 [0.86328716]]
[[0.34823425 0.19154003 0.5550761 ]
 [0.01021489 0.60645971 0.7819178 ]]
[[0.93480699 0.83888485 0.59376881]
 [0.88676701 0.24977279 0.37103991]]
[[1.28304124 1.03042488 1.14884491]
 [0.8969819  0.8562325  1.15295771]]
2.6258021623346
[[0.32263909 0.61494899 0.8373585 ]
 [0.28643643 0.30239827 0.57899311]
 [0.20750319 0.32636211 0.55092579]]
30
[[0.32553181 0.16068003 0.32958688]
 [0.00905823 2.42804553 2.10736843]]
